version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest

        steps:
            - checkout
            - run: sudo apt-get install aspell
            - run: sudo apt-get install aspell-en
            - run: find . -name "*.md" -exec cat '{}' \; | aspell list --personal=./dictionary.txt
